### ISSUE TITLE
Does not work on android

### ISSUE THREAD

**Issue by dmy3k** [cooperka/react-native-snackbar#2]
`NativeModules.RNSnackbar` is undefined. Is android platform supported?

**Comment by cooperka** [comment]
Hi @mitriy, this was a known problem that has been fixed. Please try again. I've published several fixes to npm (via my [fork](https://github.com/cooperka/react-native-snackbar)). Both android and iOS should be working now!

**Comment by joncursi** [comment]
I am running into the same issue when trying to build the app for Android:

```
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Animation.AppCompat.Dialog'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Display1'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Caption'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Caption'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Caption'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Caption'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Button'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:99:21-32 : No resource found that matches the given name: attr 'textAllCaps'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Dialog'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:118:21-36 : No resource found that matches the given name: attr 'windowActionBar'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:119:21-34 : No resource found that matches the given name: attr 'windowNoTitle'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:118:21-36 : No resource found that matches the given name: attr 'windowActionBar'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:119:21-34 : No resource found that matches the given name: attr 'windowNoTitle'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:13:56-65 : No resource found that matches the given name: attr 'elevation'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:21:64-78 : No resource found that matches the given name: attr 'backgroundTint'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:13:56-65 : No resource found that matches the given name: attr 'elevation'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:13:56-65 : No resource found that matches the given name: attr 'elevation'.
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:13:56-65 : No resource found that matches the given name: attr 'elevation'.

:react-native-snackbar:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-snackbar:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/jcursi/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by cooperka** [comment]
Hi @joncursi, make sure you've successfully run `npm install` and `react-native link react-native-snackbar` before building.

**Comment by joncursi** [comment]
@cooperka I have done that:

```
$ react-native link react-native-snackbar
rnpm-install info Android module react-native-snackbar is already linked 
rnpm-install info iOS module react-native-snackbar is already linked 
```

But the build still fails with "No resource found" errors. I have tried linking via rnpm and via react native's own implementation, no luck.

Can we supplement the instructions on your fork with manual linking instructions? Something must not be connecting properly with RNPM that I need to tweak manually. I am on React Native 0.36.0

**Comment by joncursi** [comment]
Perhaps this isn't an issue at the package layer and it's a lower level issue at the Android SDK layer.

```
/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/react-native-snackbar/android/build/intermediates/exploded-aar/com.android.support/design/23.3.0/res/values/values.xml:13:56-65 : No resource found that matches the given name: attr 'elevation'.
```

Any ideas on why these Android UI variable lookups are failing? Do I need to install something specific in the Android SDK Manager to get this to work properly?

**Comment by joncursi** [comment]
@cooperka I booted up Android Studio and it prompted me to update some SDK tools, as well as Gradle from 2.14.1 -> 2.2.2. After doing that, the project now compiles. I'm running into a few other issues, but they seem to be unrelated to this package, so I'm hoping that may have resolved it!

**Comment by cooperka** [comment]
Nice, I'm glad you got it working!

**Comment by lirbank** [comment]
I am having the exact same problem. I've upgraded Android Studio to no avail, @joncursi do you remember if there was anything else you did to get it to work?

**Comment by cooperka** [comment]
This issue was originally about a known problem that was resolved in `v0.2.0`. I'm going to close this since it's fixed, but @lirbank if you're still having trouble feel free to open a new issue!

**Comment by vicmpen** [comment]
Hey everyone,

Came up with the same problem. Upgraded Gradle to 2.2.2 and SKD Tools to latest version and project compiled!

**Comment by lirbank** [comment]
Yes, just had a chance to look at this again, and upgrading Gradle solves it. Thanks for the help!
